  
name: Test_Artifact_V2
on: [push]
jobs:      
  vm-job:
    runs-on: ubuntu-latest
    steps:
    #- run: mkdir -p path/to/artifact
    #- run: mkdir -p path/to/artifact/oneMore

    #- run: echo hello? > path/to/artifact/world.txt
      
    #- run: mkdir -p path/to/artifact2
    #- run: echo hello2 > path/to/artifact2/world2.txt
      
    # Create a large file that will be uploaded
    - run: mkdir -p path/to/big
    - run: dd if=/dev/urandom of=path/to/big/bigFile.txt bs=64M count=32
        
    - name: 'Upload Large Artifact V2'
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here
      with:
        name: 'Big-Artifact-V2'
        path: path/to/big/
    
    - name: 'Upload Large Arficact V1'
      uses: actions/upload-artifact@v1
      with:
        name: 'Big-Artifact-V1'
        path: path/to/big/
        
    # Create lots of small files that are split from a single 2MB File, each file is 50 bytes, 42k files (approx) in total
    - run: |
        mkdir -p small/files
        dd if=/dev/zero of=small/files/masterfile bs=1 count=2097152
        cd small/files
        split -b 50 -a 10 masterfile
    
    - name: 'Upload 42k Small files V1'
      uses: actions/upload-artifact@v1
      with:
        name: 'Small-Artifacts-V1'
        path: .
    #  env:
    #    https_proxy: "http://127.0.0.1:8888"
    #    http_proxy: "http://127.0.0.1:8888"
    #    NODE_TLS_REJECT_UNAUTHORIZED: "0"
      
    - name: 'Upload 42k Small files V2'
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here
      with:
        name: 'Small-Artifacts-V2'
        path: .
     # env:
     #   https_proxy: "http://127.0.0.1:8888"
     #   http_proxy: "http://127.0.0.1:8888"
     #   NODE_TLS_REJECT_UNAUTHORIZED: "0"
