  
name: Test_Artifact_V2
on: [push]
jobs:      
  v1-artifacts:
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |
        mkdir -p path/to/artifact
        echo hello > path/to/artifact/world.txt
        mkdir -p path/to/artifact2
        echo hello2 > path/to/artifact2/world2.txt
    - name: 'Upload 42k Small files'	
      uses: actions/upload-artifact@v1	
      with:	
        name: 'Small-Artifacts-V1'	
        path: .
      
  v2-artifacts:
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |	
        mkdir -p path/to/artifact
        echo hello > path/to/artifact/world.txt
        mkdir -p path/to/artifact2
        echo hello2 > path/to/artifact2/world2.txt
    - name: 'Upload 42k Small files'	
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here	
      with:	
        name: 'Small-Artifacts-V2'	
        path: .
