  
name: Test_Artifact_V2
on: [push]
jobs:      
  v1-artifacts:
    runs-on: [self-hosted]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |
        mkdir -p to-upload/artifact
        echo hello > to-upload/artifact/world.txt
        mkdir -p to-upload/artifact2
        echo hello2 > to-upload/artifact2/world2.txt
    - name: 'Upload 42k Small files'	
      uses: actions/upload-artifact@v1	
      with:	
        name: 'Artifacts-V1'	
        path: to-upload/
      
  v2-artifacts:
    runs-on: [self-hosted]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |	
        mkdir -p to-upload/artifact
        echo hello > to-upload/artifact/world.txt
        mkdir -p to-upload/artifact2
        echo hello2 > to-upload/artifact2/world2.txt
    - name: 'Upload 42k Small files'	
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here	
      with:	
        name: 'Artifacts-V2'	
        path: to-upload/
