  
name: Test_Upload_Artifact_With_Invalid_File
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - run: mkdir -p path/to/artifact
    - run: mkdir -p path/to/artifact/oneMore

    - run: echo hello > path/to/artifact/world.txt

    - name: 'Upload an Artifact'
      uses: actions/upload-artifact@releases/v1
      with:
        name: 'My-Artifact'
        path: path/to/artifact
