  
name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: [ubuntu-latest]
    env:
      name: my-artifact-name
    steps:
    - run: |
        mkdir -p to-upload/artifact
        echo This is going to be a lot of text. Repeat Repeat Repeat. The Gzip size should be less than the original > to-upload/artifact/world.txt
        mkdir -p to-upload/artifact2
        echo hello2 > to-upload/artifact2/world2.txt
        mkdir ~/to-upload
        cd ~/to-upload
        for i in {000..1000}
        do
            echo hello! > "File${i}.txt"
        done
        mkdir download-dir
    - name: 'Upload artifact'	
      uses: konradpabjan/upload-artifact@v2-preview
      with:	
        name: 'V2-Artifact'
        path: ~/to-upload/*
    
    - name: 'Upload artifact'	
      uses: konradpabjan/download-artifact@v2-preview
      with:	
        name: 'V2-Artifact'
        path: download-dir
