  
name: Test_Artifact_V2
on: [push]
jobs:           
  v2-artifacts-self-hosted:
    runs-on: self-hosted
    steps:
    - name: Print env variables
      run: |
        Get-Childitem env:
        gci env: | sort name
    - name: 'Upload Large Artifact v2'
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here
      with:
        name: 'Big-Artifact-V2-self-hosted' 
        path: C:\ArtifactTesting\ # should be 2 files, test.txt -> 50MB and test2.txt -> 1GB
        
  v1-artifacts-self-hosted:
    runs-on: self-hosted
    steps:  
    - name: Print env variables
      run: |
        Get-Childitem env:
        gci env: | sort name
    - name: 'Upload Large Artifact v1'
      uses: actions/upload-artifact@v1
      with:
        name: 'Big-Artifact-V2-self-hosted'
        path: C:\ArtifactTesting\  # should be 2 files, test.txt -> 50MB and test2.txt -> 1GB

