  
name: Test_Artifact_V2
on: [push]
jobs:      
  v1-artifacts:
    runs-on: [self-hosted]
    steps:
    - run: |
        mkdir -p to-upload/artifact
        echo hello > to-upload/artifact/world.txt
        mkdir -p to-upload/artifact2
        echo hello2 > to-upload/artifact2/world2.txt
        dd if=/dev/zero of=to-upload/outputFile bs=1G count=1
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@v1	
      with:	
        name: 'Artifacts-V1'	
        path: to-upload
      
  v2-artifacts:
    runs-on: [self-hosted]
    steps:
    - run: |	
        mkdir -p to-upload/artifact
        echo hello > to-upload/artifact/world.txt
        mkdir -p to-upload/artifact2
        echo hello2 > to-upload/artifact2/world2.txt
         dd if=/dev/zero of=to-upload/outputFile bs=1G count=1
    - name: 'Upload artifact'	
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here	
      with:	
        name: 'Artifacts-V2'	
        path: to-upload
