  
name: Test_Artifact_V2
on: [push]
jobs:      
  v1-artifacts:
    runs-on: ubuntu-latest
    steps:
    # Create a large file that will be uploaded
    - run: |
        mkdir -p path/to/big
        dd if=/dev/urandom of=path/to/big/bigFile.txt bs=64M count=32
    
    - name: 'Upload Large Arficact V1'
      uses: actions/upload-artifact@v1
      with:
        name: 'Big-Artifact-V1'
        path: path/to/big/
    
    # Create lots of small files that are split from a single 2MB File, each file is 50 bytes, 42k files (approx) in total
    - run: |
        mkdir -p small/files
        dd if=/dev/zero of=small/files/masterfile bs=1 count=2097152
        cd small/files
        split -b 50 -a 10 masterfile
    
    - name: 'Upload 42k Small files'
      uses: actions/upload-artifact@v1
      with:
        name: 'Small-Artifacts-V1'
        path: .
      
  v2-artifacts:
    runs-on: [ubuntu-latest]
    steps:
    # Create a large file that will be uploaded
    - run: |
        printenv
        mkdir -p path/to/big
        dd if=/dev/urandom of=path/to/big/bigFile.txt bs=64M count=32
        
    - name: 'Upload Large Artifact'
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here
      with:
        name: 'Big-Artifact-V2'
        path: path/to/big/
  
    # Create lots of small files that are split from a single 2MB File, each file is 50 bytes, 42k files (approx) in total
    - run: |
        mkdir -p small/files
        dd if=/dev/zero of=small/files/masterfile bs=1 count=2097152
        cd small/files
        split -b 50 -a 10 masterfile

    - name: 'Upload 42k Small files'
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here
      with:
        name: 'Small-Artifacts-V2'
        path: .
        
  v2-artifacts-self-hosted:
    runs-on: self-hosted
    steps:
    - name: Print env variables
      run: set
    - name: 'Upload Large Artifact v2'
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here
      with:
        name: 'Big-Artifact-V2-self-hosted' 
        path: C:\ArtifactTesting\ # should be 2 files, test.txt -> 50MB and test2.txt -> 1GB
        
  v1-artifacts-self-hosted:
    runs-on: self-hosted
    steps:  
    - name: Print env variables
      run: set
    - name: 'Upload Large Artifact v1'
      uses: actions/upload-artifact@v1
      with:
        name: 'Big-Artifact-V2-self-hosted'
        path: C:\ArtifactTesting\  # should be 2 files, test.txt -> 50MB and test2.txt -> 1GB

