  
name: Test_Artifact_V2
on: [push]
jobs:      
  v1-artifacts:
    runs-on: self-hosted
    steps:
    # Create a large file that will be uploaded
    - run: |
        mkdir -p path/to/big
        dd if=/dev/urandom of=path/to/big/bigFile.txt bs=64M count=32
    
    - name: 'Upload Large Arficact V1'
      uses: actions/upload-artifact@v1
      with:
        name: 'Big-Artifact-V1'
        path: path/to/big/
      
  v2-artifacts:
    runs-on: [ubuntu-latest]
    steps:
    # Create a large file that will be uploaded
    - run: |
        mkdir -p path/to/big
        dd if=/dev/urandom of=path/to/big/bigFile.txt bs=64M count=32
        
    - name: 'Upload Large Artifact'
      uses: konradpabjan/upload-artifact@konradpabjan/v2-is-almost-here
      with:
        name: 'Big-Artifact-V2'
        path: path/to/big/
